version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_branch_with_pr: true
skip_tags: true
environment:
  SonarExclusions: coverage\**\*,**\*.xml,**\*.js,tscoverage\**\*,**\jestsetup.ts,**\*.ico,**\Program.cs,**\Startup.cs,**\node_modules\*
  SonarKey:
    secure: pwFVmNEo0UwGFSQApyjms1+OFndkimAVvHLWjvqHHAvIUX1OCIvJcPKJUL1Sq50i
  SonarGithubKey:
    secure: fggX8ZEkU6nTXAwvWJLMDtlK+qpFSF1LBlPeICGpeZ+VHlY0/n0taX/uBvhoLcnw
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: >-
    cd stage4/src

    yarn install

    yarn webpack --config webpack.config.vendor.js

    yarn webpack

    cd ..

    dotnet restore

    cd ..

    choco install --no-progress sonarscanner-msbuild-netcoreapp2.0

    if ( $env:APPVEYOR_PULL_REQUEST_NUMBER )
    {
      dotnet "C:\ProgramData\chocolatey\lib\sonarscanner-msbuild-netcoreapp2.0\tools\SonarScanner.MSBuild.dll" begin /k:opensource-ci /v:$env:APPVEYOR_BUILD_VERSION /d:sonar.organization=cedricagoda-github /d:sonar.host.url=https://sonarcloud.io /d:sonar.cs.opencover.reportsPaths=coverage.xml /d:sonar.login=$env:SonarKey /d:sonar.exclusions="$env:SonarExclusions" /d:sonar.analysis.mode=preview /d:sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER /d:sonar.github.repository=$env:APPVEYOR_REPO_NAME /d:sonar.github.oauth=$env:SonarGithubKey
    }
    elseif ( $env:APPVEYOR_REPO_BRANCH -Eq "master" )
    {
      dotnet "C:\ProgramData\chocolatey\lib\sonarscanner-msbuild-netcoreapp2.0\tools\SonarScanner.MSBuild.dll" begin /k:opensource-ci /v:$env:APPVEYOR_BUILD_VERSION /d:sonar.organization=cedricagoda-github /d:sonar.host.url=https://sonarcloud.io /d:sonar.cs.opencover.reportsPaths=coverage.xml /d:sonar.login=$env:SonarKey /d:sonar.exclusions="$env:SonarExclusions"
    }    
build:
  project: stage4\opensourceci.sln
  publish_aspnet_core: true
  verbosity: minimal
test_script:
- ps: >-
    & $env:USERPROFILE\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe -register:user -oldStyle -target:"dotnet.exe" -targetargs:"test stage4\tests\tests.csproj" -filter:"+[opensourceci*]* +[tests*]*" -output:"coverage.xml"

    choco install --no-progress codecov
    
    codecov -f coverage.xml

    if ( ( $env:APPVEYOR_REPO_BRANCH -Eq "master" ) -Or $env:APPVEYOR_PULL_REQUEST_NUMBER )
    {
      dotnet "C:\ProgramData\chocolatey\lib\sonarscanner-msbuild-netcoreapp2.0\tools\SonarScanner.MSBuild.dll" end /d:sonar.login="$env:SonarKey"
    }
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true