version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_branch_with_pr: true
skip_tags: true
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: >-
    cd stage3/src

    yarn install

    yarn webpack --config webpack.config.vendor.js

    yarn webpack

    cd ..

    dotnet restore

    cd ..
build:
  project: stage3\opensourceci.sln
  publish_aspnet_core: true
  verbosity: minimal
test_script:
- ps: >-
    cd stage3/tests

    & $env:USERPROFILE\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe -register:user -oldStyle -target:"dotnet.exe" -targetargs:"test --no-build tests.csproj" -filter:"+[opensourceci*]* +[tests*]*" -output:"coverage.xml"

    # choco install codecov
    
    # codecov -f coverage.xml

    cd ../..
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true