version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: stage1.csproj
  publish_aspnet_core: true
  verbosity: minimal
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true