version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_branch_with_pr: true
skip_tags: true
environment:
  SonarExclusions: coverage\**\*,**\*.xml,**\*.js,tscoverage\**\*,**\jestsetup.ts,**\*.ico,**\Program.cs,**\Startup.cs,**\node_modules\*,**\wwwroot\dist\*
  SonarKey:
    secure: pwFVmNEo0UwGFSQApyjms1+OFndkimAVvHLWjvqHHAvIUX1OCIvJcPKJUL1Sq50i
  SonarGithubKey:
    secure: fggX8ZEkU6nTXAwvWJLMDtlK+qpFSF1LBlPeICGpeZ+VHlY0/n0taX/uBvhoLcnw
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: >-
    & .\before_build.ps1   
build:
  project: stage5\opensourceci.sln
  publish_wap_xcopy: true
  verbosity: minimal
after_build:
- ps: >-
    & .\after_build.ps1   
test_script:
- ps: >-
    & .\test_script.ps1
artifacts:
- path: publish
  type: Zip
deploy:
- provider: AzureAppServiceZipDeploy
  website: techatagoda180728-1
  username: $techatagoda18072
  password:
    secure: t2wUdySB2La3RfdpTZhkCA==
  artifact: publish.zip
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
